### ISSUE TITLE
RELEASE v1.0

### ISSUE THREAD

**Issue by dvr0** [daviderovell0/bzzzbz#31]
Now that we have all the different sections working separately we need to put everything together in a main program. The most relevant points are:
- Mapping
- Thread sync
- Real time execution.

I suggest to do this in 2 separate merging: **video<->controls** and **audio<->FFT**. We can then proceed to merge the 2 into a single program and implement the mapping. 
This will give us our first working prototype!

**Comment by dvr0** [comment]
Code and examples up and working, need to refactor, link information to documentation and tidy up for the final release.

**Comment by deetrone** [comment]
Release 1.0 is now live!
