### ISSUE TITLE
Hardware components list

### ISSUE THREAD

**Issue by voidchi** [daviderovell0/bzzzbz#61]
I would like to attempt this build, do you have a list of components required to assemble the prototype?

**Comment by dvr0** [comment]
Hello, unfortunately there's not an actual components list for v1.0. However you can find all the components in the KiCad files (schematic + PCB) in the *hardware* folder in the project repo. You can follow the wiki for a guide on how to build the hardware and assemble the software.

**Comment by voidchi** [comment]
Ace, I'll give it a shot!
