### ISSUE TITLE
fatal error: kiss_fftr.h: No such File or directory

### ISSUE THREAD

**Issue by Cevahero** [daviderovell0/bzzzbz#63]
Hi and thanks for the cool project!
Unfortunately I get this error message after `make` command. 
Maybe I am just unexperienced (total noob haha), but I followed your instructions!
Attached a screenshot, maybe you can help. thanks a lot! :)

[Screenshot](https://ibb.co/gP82Vtc)

**Comment by dvr0** [comment]
Hello,
It seems like your make doesn't find the _kiss_fftr.h_ file that is present in _src/kiss_fft/_, but I couldn't reproduce the error following the instructions.
Did you run `cmake .` before running `make`, from the repository root?

Great to know that you are trying the project out!
